Assessments

In [1]:
import numpy as np
import pandas as pd
import plotly.express as px

1. Hassan has five kinds of dogs which are husky, pitbull, shepherd, bulldog and eskimo.
Create a python program such that anyone can check if Hassan has a particular breed, if the breed is in the list of dogs print 'present' else print 'absent'. Note: use your input and conditional statements.


In [8]:
Hassan_breed = ['husky', 'pitbull', 'shepherd', 'bulldog', 'eskimo']
breed_check = input('Enter breed name: ').lower()

if breed_check in Hassan_breed:
  print('Present')
else:
  print('Absent')



Enter breed name: pit
Absent


2. Write a python program to reverse names.
E.g aloba - abola, aishat - tahsia



In [21]:
name = input('Enter name: ')[::-1]
print(name)


Enter name: lekan
nakel


3. Create a lambda function that can add two numbers and gives a result.
e.g, addition of 2 and 3 should give 5.
Use a lambda function.



In [13]:
num1 = int(input('Enter first number: '))
num2 = int(input('Enter second number: '))
sum = lambda num1, num2 : num1 + num2
print(f'{num1} + {num2} = {sum(num1, num2)}')


Enter first number: 7
Enter second number: 8
7 + 8 = 15


84. Write a function that calculates the area of a rectangle.



In [119]:
def area(l, b):
  return l*b
l=int(input('Enter length:'))
b=int(input('Enter breath:'))

Enter length:8
Enter breath:9


In [120]:
area(l,b)

72

In [23]:
import numpy as np

np.random.seed(0)  # For reproducibility
arr = np.random.randint(1, 50, size=(5, 5))
print("Generated Numpy Array:")
print(arr)

Generated Numpy Array:
[[45 48  1  4  4]
 [40 10 20 22 37]
 [24  7 25 25 13]
 [ 2 39 40 24 47]
 [25 18 38 26 14]]


5.  How can I index 38 from the array



In [25]:
arr[-1, 2]

38

6. From the array in question 5. How can I slice out [25, 25, 13], [40 , 24, 47], [38, 26, 14]


In [26]:
arr[2:, 2:]

array([[25, 25, 13],
       [40, 24, 47],
       [38, 26, 14]])

7. Create an array of zeroes of shape, (2,5)



In [28]:
array_0s = np.zeros(shape  = (2,5))
array_0s

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

8. Create an array of ones of shape (2,5)



In [29]:
array_1s = np.ones(shape  = (2,5))
array_1s

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

9. Create an array full of 6, of shape(4,4)



In [31]:
array_full = np.full(shape = (4,4), fill_value = 6)
array_full

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

10. Create a numpy array of shape (3,3) with random integers between 1 and 100.

In [121]:
import random
random_number = np.random.randint(1, 100, (3,3))
random_number

array([[66, 42, 58],
       [36, 12, 47],
       [83, 92,  1]])

**<h1><center>Pandas Assessment<center></h1>**

**<h1>Online Food Order Dataset</h1>**

**<h1>Description:</h1>**
The dataset contains information collected from an online food ordering platform over a period of time. It encompasses various attributes related to Occupation, Family Size, Feedback etc..

**<h1>Attributes:</h1>**

**<h2>Demographic Information:</h2>**

**Age:** Age of the customer.

**Gender:** Gender of the customer.

**Marital Status:** Marital status of the customer.

**Occupation:** Occupation of the customer.

**Monthly Income:** Monthly income of the customer.

**Educational Qualifications:** Educational qualifications of the customer.

**Family Size:** Number of individuals in the customer's family.

**<h2>Location Information:</h2>**

**Latitude:**Latitude of the customer's location.

**Longitude:** Longitude of the customer's location.

**Pin Code:** Pin code of the customer's location.
Order Details:**

**<h2>Purpose:</h2>**
This dataset can be utilized to explore the relationship between demographic/location factors and online food ordering behavior, analyze customer feedback to improve service quality, and potentially predict customer preferences or behavior based on demographic and location attributes.

11. Read in the dataset

In [92]:
df = pd.read_csv('/content/onlinefoods.csv')

12. Check the head of the data to get the first 10 rows

In [46]:
df.head()

Age  Gender Marital Status Occupation  Monthly Income  \
0   20  Female         Single    Student       No Income   
1   24  Female         Single    Student  Below Rs.10000   
2   22    Male         Single    Student  Below Rs.10000   
3   22  Female         Single    Student       No Income   
4   22    Male         Single    Student  Below Rs.10000   

  Educational Qualifications  Family size  latitude  longitude  Pin code  \
0              Post Graduate            4   12.9766    77.5993    560001   
1                   Graduate            3   12.9770    77.5773    560009   
2              Post Graduate            3   12.9551    77.6593    560017   
3                   Graduate            6   12.9473    77.5616    560019   
4              Post Graduate            4   12.9850    77.5533    560010   

  Output   Feedback  
0    Yes   Positive  
1    Yes   Positive  
2    Yes  Negative   
3    Yes   Positive  
4    Yes   Positive

13. Get the statistical information about the dataset

In [47]:
df.describe()

Age  Family size    latitude   longitude       Pin code
count  388.000000   388.000000  388.000000  388.000000     388.000000
mean    24.628866     3.280928   12.972058   77.600160  560040.113402
std      2.975593     1.351025    0.044489    0.051354      31.399609
min     18.000000     1.000000   12.865200   77.484200  560001.000000
25%     23.000000     2.000000   12.936900   77.565275  560010.750000
50%     24.000000     3.000000   12.977000   77.592100  560033.500000
75%     26.000000     4.000000   12.997025   77.630900  560068.000000
max     33.000000     6.000000   13.102000   77.758200  560109.000000

14. Check for the sum of missing values in each column

In [48]:
df.isnull().sum()

Age                           0
Gender                        0
Marital Status                0
Occupation                    0
Monthly Income                0
Educational Qualifications    0
Family size                   0
latitude                      0
longitude                     0
Pin code                      0
Output                        0
Feedback                      0
dtype: int64

15. Do we have duplicates in the data, if we have duplicates drop them

In [63]:
df.duplicated().sum()

0

In [62]:
df = df.drop_duplicates()

16. What is the maximum Age in the dataset?

In [64]:
df['Age'].max()

33

17. What is the minimum Age in the dataset?

In [65]:
df['Age'].min()

18

18. What is the mean Age in the dataset?

In [66]:
df['Age'].mean()

24.671232876712327

19. Do Males buy food online more than the Females

In [127]:
df['Gender'].value_counts(normalize=True)*100

Gender
Male      57.216495
Female    42.783505
Name: proportion, dtype: float64

In [124]:
df['Family size'].value_counts()

Family size
3    117
2    101
4     63
5     54
6     29
1     24
Name: count, dtype: int64

20. Do you think Singles buy food more or Married people, write a code for that

In [125]:
df['Marital Status'].value_counts(normalize=True)

Marital Status
Single               0.690722
Married              0.278351
Prefer not to say    0.030928
Name: proportion, dtype: float64

21. Let's analyse the Feedback. Do people give positive feedbacks

In [73]:
df['Feedback'].mode()[0]

'Positive'

22. Use the groupby function to groupby Gender and Marital Status, then see the average age.

In [80]:
df.groupby(['Gender','Marital Status'])['Age'].mean().reset_index()

Gender     Marital Status        Age
0  Female            Married  27.486486
1  Female  Prefer not to say  26.000000
2  Female             Single  23.207547
3    Male            Married  27.342857
4    Male  Prefer not to say  25.500000
5    Male             Single  23.195402

**<h1>Visualization</h1>**

23. Use the plotly package to create a histogram for the Age column

In [85]:
pip install plotly


In [89]:
import plotly.express as px

In [93]:
fig = px.histogram(df,x = 'Age',height = 1000, width = 1500, nbins =200)
fig.show()

24. Use the plotly package to create a bar chart for the Marital Status Column

In [95]:

fig = px.bar(df, x='Marital Status')
fig.show()
#OR


25. Use the plotly package to create a bar chart for the Gender column

In [96]:

fig = px.bar(df, x='Gender')
fig.show()

26. Use the plotly package to create a bar chart for the Occupation Column

In [97]:

fig = px.bar(df, x='Occupation')
fig.show()

27. Use the plotly package to create a pie chart for the Gender column

In [100]:
fig = px.pie(df,names='Gender')
fig.show()

28. Use the plotly package to create a bar chart for the Marital Status Column, use the Gender as the legend

In [101]:
fig = px.bar(df, x='Marital Status', color='Gender')
fig.show()

29. Use the plotly package to create a bar chart for the Gender column, use Feedback as the legend

In [102]:
fig = px.bar(df, x='Gender', color='Feedback')
fig.show()

30. Use the plotly package to create a bar chart for the Monthly Income Column and use the Gender for the legend

In [103]:
fig = px.bar(df, x='Monthly Income', color='Gender')
fig.show()

31. Create a boxplot for the Age column

In [104]:
fig = px.box(df, y="Age")
fig.show()

32. Create a boxplot, use gender as the x axis and Age for the y-axis

In [105]:
fig = px.box(df, x="Gender", y="Age")
fig.show()

33. Create a boxplot, use Marital Status as the x axis and Age for the y-axis

In [106]:
fig = px.box(df, x="Marital Status", y="Age")
fig.show()

34. Create a Violin Plot, use Monthly Income as the x axis and Age for the y-axis

In [110]:
fig = px.violin(df, x="Monthly Income", y="Age")
fig.show()

35. Create a Scatter plot, use the Latitude as x-axis and Longitude as y-axis.

In [113]:
fig = px.scatter(df, x="latitude", y="longitude")
fig.show()

36. Create a Bubble plot, use the Latitude as x-axis and Longitude as y-axis, Use the Age as the size.

In [114]:
fig = px.scatter(df, x="latitude", y="longitude",
	         size="Age")
fig.show()