In [2]:
import numpy as np

In [3]:
grades = np.array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])
grades

array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])

In [ ]:
#mean
np.mean(grades)

87.5

In [ ]:
#Median
np.median(grades)

88.5

In [ ]:
#Standard Deviation
np.std(grades)

6.591661399070799

In [ ]:
#Maximum Grade
np.max(grades)

98

In [ ]:
#Minimum Grade
np.min(grades)

75

In [ ]:
#Sorting in Ascending
np.sort(grades)

array([75, 80, 83, 85, 88, 89, 90, 92, 95, 98])

In [ ]:
 # index of the highest grade using argmax
np.argmax(grades)

7

In [ ]:
#7-Use numpy function to count the number of students who scored above 90.
np.sum(grades > 90)

3

In [4]:
#Use numpy function to calculate the percentage of students who scored above 90.
np.mean(grades > 90) * 100

30.0

In [ ]:
#Use numpy function to calculate the percentage of students who scored below 75.
np.mean(grades < 75) * 100

0.0

In [ ]:
#Use numpy function to extract all the grades above 90 and put them in a new array called "high_performers".
high_performers = grades[grades > 90]
high_performers

array([92, 95, 98])

In [ ]:
#Create a new array called "passing_grades" that contains all the grades above 75.
passing_grades = grades[grades > 75]
passing_grades

array([85, 90, 88, 92, 95, 80, 98, 89, 83])

In [ ]:
print('Mean:',np.mean(grades),'\n')
print('Median:',np.median(grades),'\n')
print('Standard Deviation:',np.std(grades),'\n')
print('Maximum Grade:',np.max(grades),'\n')
print('Minimum Grade:',np.min(grades),'\n')
print('Ascending:',np.sort(grades),'\n')
print('index of the highest grade:', np.argmax(grades),'\n')
print('Number of students that scored above 90:',np.sum(grades > 90),'\n')
print('Above score 90 percentage:', np.mean(grades > 90) * 100,'%','\n')
print('Below score 75 percentage:', np.mean(grades < 75) * 100,'%','\n')
print('Number of students that scored above 90:',high_performers,'\n')
print('Number of students that scored above 75:',passing_grades,'\n')

Mean: 87.5 

Median: 88.5 

Standard Deviation: 6.591661399070799 

Maximum Grade: 98 

Minimum Grade: 75 

Ascending: [75 80 83 85 88 89 90 92 95 98] 

index of the highest grade: 7 

Number of students that scored above 90: 3 

Above score 90 percentage: 30.0 % 

Below score 75 percentage: 0.0 % 

Number of students that scored above 90: [92 95 98] 

Number of students that scored above 75: [85 90 88 92 95 80 98 89 83] 

