In [ ]:
!pip install --upgrade pip


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 9.8 MB/s eta 0:00:00
  Attempting uninstall: pip
    Found existing installation: pip 23.1.2
    Uninstalling pip-23.1.2:
      Successfully uninstalled pip-23.1.2


In [ ]:
!pip install numpy

In [1]:
import numpy as np

In [ ]:
# Creating a 1D array
array = np.array([1, 2, 3])
print(array)

[1 2 3]


In [ ]:
import numpy as np
# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d)

[[1 2 3]
 [4 5 6]]


one of NumPy's central features, indexing.

In [ ]:
# Define a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])
# Print the array
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Print the first element of the second row
print(arr[1,0])

# Print the second element of the array
print(arr[1])

# Print the first column of the array
print(arr[:, 0])

# Negative indexing
# Define a 1D array
array2 = np.array([1, 2, 3])

# Print the last element of the array
print(array2[-1])

# Assign values to the array
arr[1, 0] = 7
print(arr)

7
[7 5 6]
[1 7]
3
[[1 2 3]
 [7 5 6]]


Array reshaping

In [ ]:
a =np.array([0,0,0,0,1,0,0,0])
a

array([0, 0, 0, 0, 1, 0, 0, 0])

In [ ]:
b = a.reshape(2,4)
b

array([[0, 0, 0, 0],
       [1, 0, 0, 0]])

Assigning Values in NumPy

In [ ]:
array_a = np.array([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array_a[0,2] = 9
array_a

array([[1, 2, 9],
       [4, 5, 6]])

In [ ]:
array_a[0] = 9
array_a

array([[9, 9, 9],
       [4, 5, 6]])

In [ ]:
array_a[:,0] = 9
array_a

array([[9, 9, 9],
       [9, 5, 6]])

In [ ]:
## Assign different values to an entire row via a list.
list_a = [8,7,8]
array_a[0] = list_a
array_a

array([[8, 7, 8],
       [9, 5, 6]])

In [ ]:
type(array_a[0])

numpy.ndarray

In [ ]:
array_a[:] = 9
array_a

array([[9, 9, 9],
       [9, 9, 9]])

In [ ]:
array_a = 9
array_a

9

In [ ]:
type(array_a)

int

PUZZLE PROGRAM

In [ ]:
array_1D = np.array([10,11,12,13, 14])
array_1D

array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_2D

array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])
array_3D

In [ ]:
#Display the first element (not necessarily individual element) for each of the 3 arrays we defined above
array_1D[:]

array([10, 11, 12, 13, 14])

In [ ]:
array_2D[0]

array([20, 30, 40, 50, 60])

In [ ]:
array_3D[0][0]

array([1, 2, 3, 4, 5])

In [ ]:
#Call the first individual element of the each of the 3 arrays.
array_1D[0]

10

In [ ]:
array_2D[:,0][0]

20

In [ ]:
array_3D[0][0][0]

1

In [ ]:
#Uses negative indices to display the last element of each array
array_1D[-1]

14

In [ ]:
array_2D[0,:][-1]

60

In [ ]:
array_3D[1][1][-1]

5

Element Wise Properties of Arrays

In [ ]:
### Multiplying each element of array_b by 2
array_a = np.array([7,8,9])
array_a

array_b = np.array([[1,2,3],[4,5,6]])
array_b

array_b = array_b * 2
array_b

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [ ]:
## Since lists don't work elementwise, we're concatenating [2] to list_a.
list_a = [1,2,3]
list_a + [2]

[1, 2, 3, 2]

In [ ]:
## Element Wise addition adds 2 to each element of array_a.
array_a + 2

array([ 9, 10, 11])

In [ ]:
## Element Wise multiplication.
## We multiply each individual element of array_a by its corresponding element in the second row of array_b.
array_a * array_b[1]

array([ 56,  80, 108])

In [ ]:
## The order of the elements matters for elementwise subtraction, division, as well as other operations.
array_b - array_a

array([[-5, -4, -3],
       [ 1,  2,  3]])

Programming puzzle

In [ ]:
array_1D = np.array([10,11,12,13, 14])
array_1D
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_2D
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])
array_3D

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 54,  5]]])

In [ ]:
#Add 2 to every element of the 3 arrays without overwriting their values.
array_1D=array_1D + 2
array_1D

array([12, 13, 14, 15, 16])

In [ ]:
array_2D=array_2D + 2
array_2D

array([[22, 32, 42, 52, 62],
       [45, 56, 67, 78, 89],
       [13, 24, 35, 46, 57]])

In [ ]:
array_3D=array_3D + 2
array_3D

array([[[ 3,  4,  5,  6,  7],
        [13, 23, 33, 43, 53]],

       [[13, 14, 15, 16, 17],
        [53, 54, 55, 56,  7]]])

In [ ]:
#Multiply the values of each array by 100 without overwriting their values.
array_1D *100

array([1200, 1300, 1400, 1500, 1600])

In [ ]:
array_2D *100

array([[2200, 3200, 4200, 5200, 6200],
       [4500, 5600, 6700, 7800, 8900],
       [1300, 2400, 3500, 4600, 5700]])

In [ ]:
array_3D *100

array([[[ 300,  400,  500,  600,  700],
        [1300, 2300, 3300, 4300, 5300]],

       [[1300, 1400, 1500, 1600, 1700],
        [5300, 5400, 5500, 5600,  700]]])

Types of Data Supported by Numpy

In [ ]:
array_a = np.array([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Defining all the values as floats (decimals).
array_a = np.array([[1,2,3],[4,5,6]], dtype = np.float16)
array_a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float16)

In [ ]:
# Defining all the values as complex numbers.
array_a = np.array([[1,2,3],[4,5,6]], dtype = np.complex64)
array_a

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]], dtype=complex64)

In [ ]:
# Defining all the values as Booleans.
array_a = np.array([[1,2,0],[4,5,6]], dtype = np.bool_)
array_a

array([[ True,  True, False],
       [ True,  True,  True]])

In [ ]:
# Defining all the values as text.
array_a = np.array([[10,2,3],[4,5,6]], dtype = np.str_)
array_a

array([['10', '2', '3'],
       ['4', '5', '6']], dtype='<U2')

Programming puzzle

In [ ]:
import numpy as np
array_1D = np.array([10,11,12,13,14])
array_1D

array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_2D

array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])
array_3D

In [4]:
#array_1D -> NumPy Strings
array_1D = np.array([10,11,12,13,14], dtype= np.str_)

In [5]:
#array_2D -> Complex Numbers
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]], dtype=np.complex64)

In [9]:
#array_3D -> 64-bit Floats
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]], dtype=np.float_)

Basics slicing

In [10]:
matrix_A = np.array([[1,2,3],[4,5,6]])
matrix_A

matrix_A[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
## [:2] -> All the rows up to the 3rd one (excluding the third one).
matrix_A[:2]


array([[1, 2, 3]])

In [13]:
# [:-1] -> All the rows up to the last one.
matrix_A[:-1]

array([[1, 2, 3]])

stepwise slicing

In [15]:
# The syntax for each dimension is "[start : stop : step]".
matrix_B = np.array([[1,1,1,2,0], [3,6,6,7,4], [4,5,3,8,0]])
matrix_B

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [16]:
matrix_B[:,::2]

array([[1, 1, 0],
       [3, 6, 4],
       [4, 3, 0]])

Programming puzzle

In [37]:
array_1D = np.array([10,11,12,13, 14])
array_1D

array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_2D

array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])
array_3D

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 54,  5]]])

In [ ]:
array_2D = np.array([[20,30,40,50,60],[43,54,65,76,87],[11,22,33,44,55]])
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 44, 55]])

In [40]:
array_2D[1, 3:5]

array([76, 87])

In [18]:
array_3D

array([[[ 1.,  2.,  3.,  4.,  5.],
        [11., 21., 31., 41., 51.]],

       [[11., 12., 13., 14., 15.],
        [51., 52., 53., 54.,  5.]]])

In [39]:
array_2D[1,0:3]

array([43, 54, 65])

**Generating data with numpy**


With numpy, you can use functions like np.random.rand, np.random.randn, and np.random.random_sample to generate arrays of random numbers with various distributions, such as uniform, normal, and more.

In [41]:
#Arrays of empty :
array_empty = np.empty(shape = (2,3))
array_empty

array([[ 4.94162937e-310,  0.00000000e+000, -3.50531531e+231],
       [ 7.07650310e-294,  5.65622612e+303,  2.44969211e-149]])

In [42]:
# zeros
array_0s = np.zeros(shape  = (2,3))
array_0s


array([[0., 0., 0.],
       [0., 0., 0.]])

In [43]:
array_0s = np.zeros(shape = (2,3), dtype = np.int8)
array_0s

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [44]:
# ones
array_1s = np.ones(shape  = (2,3))
array_1s

array([[1., 1., 1.],
       [1., 1., 1.]])

In [46]:
# full
array_full = np.full(shape = (2,3), fill_value = 2)
array_full

array([[2, 2, 2],
       [2, 2, 2]])

In [47]:
# One additional mandatory argument - fill_value -> scalar
array_full
array_full = np.full(shape = (2,3), fill_value = 'Three-Six-Five')
array_full

array([['Three-Six-Five', 'Three-Six-Five', 'Three-Six-Five'],
       ['Three-Six-Five', 'Three-Six-Five', 'Three-Six-Five']],
      dtype='<U14')

**_like Function :**

In NumPy, the "like" function is used to create a new array with the same shape and type as an existing array.

In [49]:
matrix_A = np.array([[1,0,9,2,2],[3,23,4,5,1],[0,2,3,4,1]])
matrix_A

#Empty
array_empty_like = np.empty_like(matrix_A)
array_empty_like

array([[    100019732453354,                   0,                   0,
                          0,                   0],
       [8319683848551211643, 3180222411935070754, 8391722768137527840,
        7959390389040738153, 2318288605207470708],
       [8675445202132104482, 7957695011165139568, 2318365875964093043,
        7233184988217307170,                 128]])

In [50]:
#Zeros
array_0s_like = np.zeros_like(matrix_A)
print(array_0s_like)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


Arrange function:

In NumPy, the "arange" function is used to create an array with evenly spaced values within a given range. The function is similar to the built-in Python range function, but it returns a NumPy array instead of a list.

In [53]:
list(range(8))

[0, 1, 2, 3, 4, 5, 6, 7]

In [54]:
## Creates an ndarray with the values in this range.
array_rng = np.arange(30)
array_rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [56]:
# array_rng = np.arange(stop =  30)
array_rng = np.arange(stop =  30)
array_rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [57]:
# If we specify only a start, the function assumes this is the "stop" and starts from the origin (0).
array_rng = np.arange(start = 0, stop =  30)
array_rng


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [58]:
# "Step" doesn't have to be the same type as the values of the array.
array_rng = np.arange(start = 0, stop =  30, step = 2.5)
array_rng

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5, 25. ,
       27.5])

In [59]:
# The casting happens after all the computations.
array_rng = np.arange(start = 0, stop =  30, step = 2.5, dtype = np.float32)
array_rng = np.arange(start = 0, stop =  30, step = 2.5, dtype = np.int32)
array_rng

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22], dtype=int32)

Programming puzzle.

In [65]:
#The first one should be "empty"
empty_array = np.empty(shape = (4,10))
empty_array

array([[4.94162937e-310, 0.00000000e+000, 6.78408017e-310,
        6.78408017e-310, 6.78408019e-310, 6.78408019e-310,
        6.78408017e-310, 6.78414358e-310, 6.78408018e-310,
        6.78414358e-310],
       [6.78408018e-310, 6.78408017e-310, 6.78408018e-310,
        6.78414358e-310, 6.78408017e-310, 6.78414358e-310,
        6.78408017e-310, 6.78408017e-310, 6.78408019e-310,
        6.78408017e-310],
       [6.78408018e-310, 6.78414353e-310, 6.78414348e-310,
        6.78414353e-310, 6.78409872e-310, 6.78414348e-310,
        6.78408018e-310, 6.78414348e-310, 6.78409872e-310,
        6.78414348e-310],
       [0.00000000e+000, 4.00193173e-322, 4.94043813e-310,
        6.78414389e-310, 0.00000000e+000, 2.42092166e-322,
        4.94043805e-310, 6.78414389e-310, 0.00000000e+000,
        0.00000000e+000]])

In [66]:
#The second one should be full of 0s
zeros_array = np.zeros(shape = (4,10))
zeros_array

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [68]:
#The third one should be full of 1s
full_array = np.full(shape = (4,10), fill_value=1)
full_array

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [69]:
#The last one should be full of 2s
full_array = np.full(shape = (4,10), fill_value=2)
full_array

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])

**Statistics with NumPy**

In [70]:
#Mean function :
x = np.array([1, 2, 3, 4, 5])
print(np.mean(x))

3.0


In [73]:
#Calculating the mean for each column
x = np.array([[1, 2, 3], [4, 5, 6]])
print(np.mean(x, axis=0))

[2.5 3.5 4.5]


In [6]:
matrix_A = np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])
matrix_A

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

In [10]:
np.argmin(matrix_A)

1

In [10]:
#minimum/maximum in the entire array
print("Minimum value using np.min: ",np.min(matrix_A))
print("Maximum value using np.max: ",np.max(matrix_A))

# Find the minimum/maximum value along a specific axis=0 (along columns)
print("Minimum value using np.amin along axis 0: ",np.amin(matrix_A, axis=0))
print("Maximum value using np.amax along axis 0: ",np.amax(matrix_A, axis=0))

# Find the minimum/maximum value along a specific axis=1 (along rows)
print("Minimum value using np.amin along axis 1: ",np.amin(matrix_A, axis=1))
print("Maximum value using np.amax along axis 1: ",np.amax(matrix_A, axis=1))

# Compute the minimum/maximum value along axis 0 (column-wise) using np.minimum.reduce
print("Minimum value using np.minimum.reduce: ",np.minimum.reduce(matrix_A))
print("Maximum value using np.maximum.reduce: ",np.maximum.reduce(matrix_A))

Minimum value using np.min:  0
Maximum value using np.max:  9
Minimum value using np.amin along axis 0:  [1 0 0 2 0]
Maximum value using np.amax along axis 0:  [4 6 6 8 9]
Minimum value using np.amin along axis 1:  [0 2 0]
Maximum value using np.amax along axis 1:  [3 9 8]
Minimum value using np.minimum.reduce:  [1 0 0 2 0]
Maximum value using np.maximum.reduce:  [4 6 6 8 9]


Averages and Variances:

In [23]:
matrix_A = np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])

# Find the Median value along a specific axis
print("Median value along axis 0: ",np.median(matrix_A, axis=0))
print("Median value along axis 1: ",np.median(matrix_A, axis=1))
print('\n')

# Find the Mean value along a specific axis
print("Mean value along axis 0: ",np.mean(matrix_A, axis=0))
print("Mean value along axis 1: ",np.mean(matrix_A, axis=1))
print('\n')

# Find the Variance value along a specific axis
print("Variance value along axis 0: ",np.var(matrix_A, axis=0))
print("Variance value along axis 1: ",np.var(matrix_A, axis=1))
print('\n')

# Find the Standard Deviation value along a specific axis
print("Standard Deviation value along axis 0: ",np.std(matrix_A, axis=0))
print("Standard Deviation value along axis 1: ",np.std(matrix_A, axis=1))
print('\n')

# Find the Average value along a specific axis
print("Variance value along axis 0: ",np.average(matrix_A, axis=0))
print("Variance value along axis 1: ",np.average(matrix_A, axis=1))


Median value along axis 0:  [3. 5. 3. 3. 1.]
Median value along axis 1:  [1. 6. 4.]


Mean value along axis 0:  [2.66666667 3.66666667 3.         4.33333333 3.33333333]
Mean value along axis 1:  [1.  5.2 4. ]


Variance value along axis 0:  [ 1.55555556  6.88888889  6.          6.88888889 16.22222222]
Variance value along axis 1:  [1.2  6.16 6.8 ]


Variance value along axis 0:  [1.24721913 2.62466929 2.44948974 2.62466929 4.02768199]
Variance value along axis 1:  [1.09544512 2.48193473 2.60768096]


Variance value along axis 0:  [2.66666667 3.66666667 3.         4.33333333 3.33333333]
Variance value along axis 1:  [1.  5.2 4. ]


Covariance and correlation :

In [24]:
#Covariance
matrix_A = np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])
cov_matrix = np.cov(matrix_A)
print("Covariance matrix of matrix_A : \n",cov_matrix)

Covariance matrix of matrix_A : 
 [[ 1.5 -2.   2. ]
 [-2.   7.7 -7. ]
 [ 2.  -7.   8.5]]


In [25]:
#Correlation
matrix_A = np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])
corr_matrix = np.corrcoef(matrix_A)
print("Correlation matrix of matrix_A : \n",corr_matrix)

Correlation matrix of matrix_A : 
 [[ 1.         -0.58848989  0.56011203]
 [-0.58848989  1.         -0.8652532 ]
 [ 0.56011203 -0.8652532   1.        ]]


In [4]:
# create an array with some values
apl = np.array([1, 2, 3, 4, 5], dtype=float)
# set the second element to NaN
apl[1] = np.nan
print(apl)

[ 1. nan  3.  4.  5.]
